# Generated by Django 3.1.7 on 2021-03-26 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(default='', max_length=200)),
                ('blogimage', models.CharField(default='', max_length=200)),
                ('blogdesc', models.TextField(default='')),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('lan', models.PositiveIntegerField()),
                ('catimage', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='categoryDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.PositiveIntegerField(default=0)),
                ('cat_name', models.CharField(default='no', max_length=200)),
                ('image', models.CharField(default='no', max_length=200)),
                ('position', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='homepageProdects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.PositiveIntegerField(default=0)),
                ('subcat_id', models.PositiveIntegerField(default=0)),
                ('cat_name', models.CharField(default='no', max_length=100)),
                ('subcat_name', models.CharField(default='no', max_length=100)),
                ('prodect_id', models.CharField(default='no', max_length=100)),
                ('prodect_name', models.CharField(default='no', max_length=200)),
                ('image', models.CharField(default='no', max_length=200)),
                ('postion_name', models.CharField(default='no', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_link', models.CharField(max_length=200)),
                ('lan', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orderProdects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField(default=0)),
                ('orderId', models.CharField(default='', max_length=200)),
                ('prodectId', models.CharField(default='', max_length=200)),
                ('prodectName', models.CharField(default='', max_length=200)),
                ('prodectPrice', models.CharField(default='', max_length=200)),
                ('prodectImage', models.CharField(default='', max_length=200)),
                ('quantity', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField(default=0)),
                ('username', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('orderId', models.CharField(default='', max_length=200)),
                ('totalPrice', models.CharField(default='', max_length=200)),
                ('subtotalPrice', models.CharField(default='', max_length=200)),
                ('shippingprice', models.CharField(default='', max_length=200)),
                ('orderDate', models.CharField(default='', max_length=50)),
                ('develiveryDate', models.CharField(default='', max_length=50)),
                ('shippingAddras', models.TextField(blank=True, null=True)),
                ('orderState', models.CharField(default='1', max_length=200)),
                ('odertype', models.CharField(default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prodects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.PositiveIntegerField()),
                ('subcat_id', models.PositiveIntegerField()),
                ('cat_name', models.CharField(max_length=100)),
                ('subcat_name', models.CharField(max_length=100)),
                ('lan', models.CharField(default='', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('oldPrice', models.CharField(max_length=100)),
                ('discount', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100)),
                ('sliderdescription', models.TextField()),
                ('description', models.TextField()),
                ('productdetails', models.TextField()),
                ('images', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('thumbimg', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('slider', models.CharField(default='no', max_length=100)),
                ('preference_pricing', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('url', models.CharField(default='no', max_length=100)),
                ('addedby', models.CharField(default='no', max_length=100)),
                ('state', models.PositiveIntegerField(default=0)),
                ('approved', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sitesettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='no', max_length=200)),
                ('site_phone', models.CharField(default='no', max_length=200)),
                ('site_email', models.CharField(default='no', max_length=200)),
                ('site_logo', models.CharField(default='', max_length=200)),
                ('footer_text', models.CharField(default='no', max_length=200)),
                ('copyright', models.CharField(default='no', max_length=200)),
                ('reference_pricing', models.PositiveIntegerField(default=0)),
                ('sitestatus', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prodectid', models.PositiveIntegerField(default=0)),
                ('prodecturl', models.CharField(default='', max_length=200)),
                ('images', models.TextField(blank=True, null=True)),
                ('pos', models.PositiveIntegerField(default=1)),
                ('status', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='specialofferProdects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodectid', models.PositiveIntegerField(default=0)),
                ('prodect_name', models.CharField(default='no', max_length=200)),
                ('image', models.CharField(default='no', max_length=200)),
                ('text', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.PositiveIntegerField()),
                ('cat_name', models.CharField(max_length=100)),
                ('subcat_name', models.CharField(max_length=100)),
                ('lan', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(default=0)),
                ('prodectid', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
