# Generated by Django 3.1.5 on 2021-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprodects',
            name='prodect_addedby',
            field=models.CharField(default='', max_length=200),
        ),
    ]
